dependencies {
    implementation project(':module-common')
    implementation project(':module-member')

    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
}

tasks.register('copyExternalConfigs', Copy) {
    from(project(':module-member').file('src/main/resources/application-member.yml'))
    into(layout.buildDirectory.dir("resources/main"))
}

processResources.dependsOn(copyExternalConfigs)